{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "tor-android",
    "version": "0.4.8.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.8.13.2.aar",
          "url": "tor-android-0.4.8.13.2.aar",
          "size": 13040921,
          "sha512": "b7cff4c182afc3fefde1dab5d80249fac959912de71949fbeba2d0bfd8b6055884dd61bb7ad39c3364bc2d859ec9adb33d6076043c11b35f49e55a69e2765d0b",
          "sha256": "2fe4451cbd8ec28293cf364347a285ed5bb8baec98b80b8b969ab1d70956feeb",
          "sha1": "2d3618bcfe7577f2edb1a3cbe3e4c26f53b4e492",
          "md5": "02b52295b0abccd46d08deecf037a87f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.8.13.2.aar",
          "url": "tor-android-0.4.8.13.2.aar",
          "size": 13040921,
          "sha512": "b7cff4c182afc3fefde1dab5d80249fac959912de71949fbeba2d0bfd8b6055884dd61bb7ad39c3364bc2d859ec9adb33d6076043c11b35f49e55a69e2765d0b",
          "sha256": "2fe4451cbd8ec28293cf364347a285ed5bb8baec98b80b8b969ab1d70956feeb",
          "sha1": "2d3618bcfe7577f2edb1a3cbe3e4c26f53b4e492",
          "md5": "02b52295b0abccd46d08deecf037a87f"
        }
      ]
    }
  ]
}
