{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject.keanuapp",
    "module": "keanulib",
    "version": "0.5.83",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.16.1"
          }
        },
        {
          "group": "matrix",
          "module": "sdk2",
          "version": {
            "requires": "1.5.26"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.16.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.16.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "keanulib-0.5.83.aar",
          "url": "keanulib-0.5.83.aar",
          "size": 3416164,
          "sha512": "742c28fba050ba511ef27fd7473dee0683bd5795af41c2d538c4a0e1f0070540bc7160bdf7bc814a5e3c3c1a4f188aa810ddf0d1a25da663424eb7d787af5a0b",
          "sha256": "d751e3f97d554769f5f92e91266823454f82b216aad925b9f9e1615966e992e9",
          "sha1": "d431558c4ee8fd2bfcfef07691cc4942ce07fb8f",
          "md5": "3d0066e346c1dbb945ad32872fff7553"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-bom",
          "version": {
            "requires": "4.9.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection"
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "ru.noties.markwon",
          "module": "core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "com.github.Zhuinden",
          "module": "realm-monarchy",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-instances-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.45"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "transcoder",
          "version": {
            "requires": "0.10.5"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "info.guardianproject.panic",
          "module": "panic",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "org.ocpsoft.prettytime",
          "module": "prettytime",
          "version": {
            "requires": "4.0.6.Final"
          }
        },
        {
          "group": "com.theartofdev.edmodo",
          "module": "android-image-cropper",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.QuadFlask",
          "module": "colorpicker",
          "version": {
            "requires": "0.0.15"
          }
        },
        {
          "group": "agency.tango.android",
          "module": "avatar-view",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "agency.tango.android",
          "module": "avatar-view-glide",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "autocomplete",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.stefanosiano.powerful_libraries",
          "module": "imageview_rs",
          "version": {
            "requires": "1.0.15"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.jcodec",
          "module": "jcodec",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "com.gsconrad",
          "module": "richcontentedittext",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "richeditor-android",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.github.n8fr8",
          "module": "AudioRecorderView",
          "version": {
            "requires": "228d48dbbc"
          }
        },
        {
          "group": "com.vanniktech",
          "module": "emoji-google",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "com.github.lwj1994",
          "module": "Matisse",
          "version": {
            "requires": "bc1d6ac4d0"
          }
        },
        {
          "group": "com.github.ybq",
          "module": "Android-SpinKit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.thealeksandr",
          "module": "PFLockScreen-Android",
          "version": {
            "requires": "1.0.0-beta7"
          }
        },
        {
          "group": "org.cleaninsights.sdk",
          "module": "clean-insights-sdk",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "29.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging-ktx"
        },
        {
          "group": "io.getstream",
          "module": "avatarview-coil",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.myinnos",
          "module": "AppIconNameChanger",
          "version": {
            "requires": "1.0.7"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.16.1"
          }
        },
        {
          "group": "matrix",
          "module": "sdk2",
          "version": {
            "requires": "1.5.26"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.0.2"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.16.1"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.16.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "keanulib-0.5.83.aar",
          "url": "keanulib-0.5.83.aar",
          "size": 3416164,
          "sha512": "742c28fba050ba511ef27fd7473dee0683bd5795af41c2d538c4a0e1f0070540bc7160bdf7bc814a5e3c3c1a4f188aa810ddf0d1a25da663424eb7d787af5a0b",
          "sha256": "d751e3f97d554769f5f92e91266823454f82b216aad925b9f9e1615966e992e9",
          "sha1": "d431558c4ee8fd2bfcfef07691cc4942ce07fb8f",
          "md5": "3d0066e346c1dbb945ad32872fff7553"
        }
      ]
    }
  ]
}
