{
  "formatVersion": "1.1",
  "component": {
    "group": "org.torproject",
    "module": "arti-mobile",
    "version": "1.7.0-debug",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-1.7.0-debug.aar",
          "url": "arti-mobile-1.7.0-debug.aar",
          "size": 19664499,
          "sha512": "cd41a8a43b58bb95c3a2f59b002e7940edf8d6c3636a4931f69a11232e998f0436f76b4c4609ff0bb7254323327cd56578d3c7193ba4a70817f70f0190fc795d",
          "sha256": "6815aec06b3caa7e4748921c23cd7ca6c7abafde506561681f17129c92b8f485",
          "sha1": "7bfb7356646457e486f6e079721520b9fd3e2cc3",
          "md5": "7d3a19a2a127cc94fe10ef3923f9f5d4"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-1.7.0-debug.aar",
          "url": "arti-mobile-1.7.0-debug.aar",
          "size": 19664499,
          "sha512": "cd41a8a43b58bb95c3a2f59b002e7940edf8d6c3636a4931f69a11232e998f0436f76b4c4609ff0bb7254323327cd56578d3c7193ba4a70817f70f0190fc795d",
          "sha256": "6815aec06b3caa7e4748921c23cd7ca6c7abafde506561681f17129c92b8f485",
          "sha1": "7bfb7356646457e486f6e079721520b9fd3e2cc3",
          "md5": "7d3a19a2a127cc94fe10ef3923f9f5d4"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "arti-mobile-1.7.0-debug-sources.jar",
          "url": "arti-mobile-1.7.0-debug-sources.jar",
          "size": 10071,
          "sha512": "698ee3d12f4998dcb777557d01b783095618ded7b2b85b8296c27fdec068532553fa04f6062094d080a7746534f0efb6bf2f8c8d1a6ec4957e9e7d0eb22df2b1",
          "sha256": "236b2b7348b8624f64a2d80ce33efe39a508f7d9dd50ef70e0a1168d514b5aa2",
          "sha1": "05cc19cf1c6578f9a218e636968f37f2bffc7824",
          "md5": "ac8ecb0342fe65108c5ca5dc3208ad1b"
        }
      ]
    }
  ]
}
