{
  "formatVersion": "1.1",
  "component": {
    "group": "org.torproject",
    "module": "arti-mobile",
    "version": "1.7.0-debug",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-1.7.0-debug.aar",
          "url": "arti-mobile-1.7.0-debug.aar",
          "size": 19664433,
          "sha512": "bdf2ab0cde47d7acef9203e53bf8c9454ca531c0645d16de2dd7da26092f6fc48a932ec53280a9e7eccc7a71c0e2bbec809fb80aa72ba19072fa507a7965634c",
          "sha256": "9c78750a4f3d874fbfb4f2064a3366a4abc9e9633c2537e7906a5311aa144c97",
          "sha1": "14009e0d62b745edf5386670e8a2b1cca42aa47e",
          "md5": "d21aa2e3318f8e376a72cf598d9175b3"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-1.7.0-debug.aar",
          "url": "arti-mobile-1.7.0-debug.aar",
          "size": 19664433,
          "sha512": "bdf2ab0cde47d7acef9203e53bf8c9454ca531c0645d16de2dd7da26092f6fc48a932ec53280a9e7eccc7a71c0e2bbec809fb80aa72ba19072fa507a7965634c",
          "sha256": "9c78750a4f3d874fbfb4f2064a3366a4abc9e9633c2537e7906a5311aa144c97",
          "sha1": "14009e0d62b745edf5386670e8a2b1cca42aa47e",
          "md5": "d21aa2e3318f8e376a72cf598d9175b3"
        }
      ]
    },
    {
      "name": "debugSourcesElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "arti-mobile-1.7.0-debug-sources.jar",
          "url": "arti-mobile-1.7.0-debug-sources.jar",
          "size": 9915,
          "sha512": "a7f56eaae55cb8433a6d69a441c5b728b5ae592f1f2e43db86391ecfb097ee28f648486c16939dc9d828e3bacd0c8081566ad68e183ef535f20ac1f024c5b17e",
          "sha256": "891a279a6ca23de3b56deda41cefaabc61788b89b5e85f3e7a93649c03a0ca90",
          "sha1": "26ab6058ab99f0c303a700c396b56aa951a24fa0",
          "md5": "ef33e47485828461d7880210edaf5781"
        }
      ]
    }
  ]
}
