{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "durindoor",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "durindoor-0.0.8.aar",
          "url": "durindoor-0.0.8.aar",
          "size": 471406,
          "sha512": "308c5d0a119184d1ee984bf40e52d82adcc82a1531af1dee6fc0023c6aa3fe0314ae30b5b4f0b089ae3444a7048b43550b95cc04c582eea5f7ef6cb147233361",
          "sha256": "758f6d71d984166006f98a7e1b46ac5425459b51a4976b96a34bf666097d9831",
          "sha1": "883227b16072d9c0a6fdb66b782cd8b432a9b7a2",
          "md5": "feb76122ff3152a4bd0fb2eedc451bf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "durindoor-0.0.8.aar",
          "url": "durindoor-0.0.8.aar",
          "size": 471406,
          "sha512": "308c5d0a119184d1ee984bf40e52d82adcc82a1531af1dee6fc0023c6aa3fe0314ae30b5b4f0b089ae3444a7048b43550b95cc04c582eea5f7ef6cb147233361",
          "sha256": "758f6d71d984166006f98a7e1b46ac5425459b51a4976b96a34bf666097d9831",
          "sha1": "883227b16072d9c0a6fdb66b782cd8b432a9b7a2",
          "md5": "feb76122ff3152a4bd0fb2eedc451bf1"
        }
      ]
    }
  ]
}
