{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject.keanuapp",
    "module": "keanulib",
    "version": "0.0.5.60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.8.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.8.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.8.0"
          }
        },
        {
          "group": "org.matrix.android",
          "module": "matrix-android-sdk2",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "keanulib-0.0.5.60.aar",
          "url": "keanulib-0.0.5.60.aar",
          "size": 2310433,
          "sha512": "937cbfd89586ba911999924aa281e52a499989a292562f761d52fef4827f6559c1cbb7ce8ab7cec518a5d2fdce674c291da6c878440b388eac010796cd3acf4c",
          "sha256": "bed0c25f6c4028041ffe44e162592df8943bd9cd0c82e85505491cdc65b35c2f",
          "sha1": "47756825222845708a214f5503a861f3dd52893e",
          "md5": "b582d23b2293941d6f07abfc734bee36"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.8.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.8.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.8.0"
          }
        },
        {
          "group": "org.matrix.android",
          "module": "matrix-android-sdk2",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-bom",
          "version": {
            "requires": "4.9.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection"
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ru.noties.markwon",
          "module": "core",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.Zhuinden",
          "module": "realm-monarchy",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-instances-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.38.1"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "transcoder",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.matrix.gitlab.matrix-org",
          "module": "olm",
          "version": {
            "requires": "3.2.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "info.guardianproject.panic",
          "module": "panic",
          "version": {
            "requires": "0.5"
          }
        },
        {
          "group": "org.ocpsoft.prettytime",
          "module": "prettytime",
          "version": {
            "requires": "4.0.1.Final"
          }
        },
        {
          "group": "com.theartofdev.edmodo",
          "module": "android-image-cropper",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.github.QuadFlask",
          "module": "colorpicker",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "agency.tango.android",
          "module": "avatar-view",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "agency.tango.android",
          "module": "avatar-view-glide",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "com.stefanosiano.powerful_libraries",
          "module": "imageview_rs",
          "version": {
            "requires": "1.0.15"
          }
        },
        {
          "group": "com.github.barteksc",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "org.jcodec",
          "module": "jcodec",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.gsconrad",
          "module": "richcontentedittext",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "jp.wasabeef",
          "module": "richeditor-android",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.github.n8fr8",
          "module": "AudioRecorderView",
          "version": {
            "requires": "228d48dbbc"
          }
        },
        {
          "group": "com.vanniktech",
          "module": "emoji-google",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.github.lwj1994",
          "module": "Matisse",
          "version": {
            "requires": "bc1d6ac4d0"
          }
        },
        {
          "group": "com.github.ybq",
          "module": "Android-SpinKit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.thealeksandr",
          "module": "PFLockScreen-Android",
          "version": {
            "requires": "1.0.0-beta7"
          }
        },
        {
          "group": "org.cleaninsights.sdk",
          "module": "clean-insights-sdk",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "keanulib-0.0.5.60.aar",
          "url": "keanulib-0.0.5.60.aar",
          "size": 2310433,
          "sha512": "937cbfd89586ba911999924aa281e52a499989a292562f761d52fef4827f6559c1cbb7ce8ab7cec518a5d2fdce674c291da6c878440b388eac010796cd3acf4c",
          "sha256": "bed0c25f6c4028041ffe44e162592df8943bd9cd0c82e85505491cdc65b35c2f",
          "sha1": "47756825222845708a214f5503a861f3dd52893e",
          "md5": "b582d23b2293941d6f07abfc734bee36"
        }
      ]
    }
  ]
}
