{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "tor-android",
    "version": "0.4.9.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.13.2.aar",
          "url": "tor-android-0.4.9.13.2.aar",
          "size": 12960573,
          "sha512": "3fc357f43b9a66324204dbdee8f87ba7ef24c0ae0928f0d60131dddf7bfb887bb04c1f41b78f6bcb0110662fd1c036d468b8e196f10e1925701aaa17c5983d2d",
          "sha256": "40be745450a8ecfaac8558950bf046f596d7ef6e88107f69334a8c4b6e7d14be",
          "sha1": "bb9045662b2c07578e0092c3ea5d384f29ddc111",
          "md5": "7e175e61a961bebc00a2af56b9e2e947"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.13.2.aar",
          "url": "tor-android-0.4.9.13.2.aar",
          "size": 12960573,
          "sha512": "3fc357f43b9a66324204dbdee8f87ba7ef24c0ae0928f0d60131dddf7bfb887bb04c1f41b78f6bcb0110662fd1c036d468b8e196f10e1925701aaa17c5983d2d",
          "sha256": "40be745450a8ecfaac8558950bf046f596d7ef6e88107f69334a8c4b6e7d14be",
          "sha1": "bb9045662b2c07578e0092c3ea5d384f29ddc111",
          "md5": "7e175e61a961bebc00a2af56b9e2e947"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.13.2-sources.jar",
          "url": "tor-android-0.4.9.13.2-sources.jar",
          "size": 6654,
          "sha512": "b98440be4859efe0408f50b818f30f2990a054d7ad32aebca3c4442d72cd7ea07f1197150ad3498979f6f053b60c0c90b5a449512e3e070e1c126ca1a3a276f9",
          "sha256": "57bf8fee8ae70af4333769c3ed8af11bad16795579c8c2da7bbde7cc1d23b3fb",
          "sha1": "9a9142849c0e8b3da2c3249d593af88dff197965",
          "md5": "d027fb4f7849a7be8299828f02419b0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.13.2-javadoc.jar",
          "url": "tor-android-0.4.9.13.2-javadoc.jar",
          "size": 455484,
          "sha512": "ad16cb96f24ee74147dd4be953970871b9371fc176aeb91d0fdbc5ded83c7eb4f98aa0f7d0b0d5a08d3636f1ae1db62fd8cf98fda9f932b4151cfa4d8f86133c",
          "sha256": "9a70085f7f2e05337620b305c0f55a4fb220b31ecc00299bfe8080e482c8c859",
          "sha1": "fa0e812bb1ed0829913bcb85cb45b21e37ad68b8",
          "md5": "b570008c33ff7a71aef44b484598e72c"
        }
      ]
    }
  ]
}
