{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "tor-android",
    "version": "0.4.9.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.13.aar",
          "url": "tor-android-0.4.9.13.aar",
          "size": 12957526,
          "sha512": "a3d0fc1e821b5b7e7d3a7c6a5f40f379b3d62464f3c44c080343301378003c3e9908a7bfbdea77fe8d4476853b537a6c2fc09792a5e74ea176646c1c95b7b326",
          "sha256": "6a1fd13e9961e5398fe73e4dc507a859431ed7998f229b121d43dcc56b311b0a",
          "sha1": "0501d4a068a7a921fe11adc241b2daa32190518f",
          "md5": "dabf0b80c7dea416b0b8d765ec0d517f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.13.aar",
          "url": "tor-android-0.4.9.13.aar",
          "size": 12957526,
          "sha512": "a3d0fc1e821b5b7e7d3a7c6a5f40f379b3d62464f3c44c080343301378003c3e9908a7bfbdea77fe8d4476853b537a6c2fc09792a5e74ea176646c1c95b7b326",
          "sha256": "6a1fd13e9961e5398fe73e4dc507a859431ed7998f229b121d43dcc56b311b0a",
          "sha1": "0501d4a068a7a921fe11adc241b2daa32190518f",
          "md5": "dabf0b80c7dea416b0b8d765ec0d517f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.13-sources.jar",
          "url": "tor-android-0.4.9.13-sources.jar",
          "size": 6654,
          "sha512": "26a8bf6829a4a964fa2c91227fcf03f6b1dfae9718698d033d52d303d7eeb52934bf290710230ac2337b5dab00d4df68d052021d81c686063e169d78cffbe866",
          "sha256": "7b01431ff4d50e82514b15f706ff5b32d6cf33a71bd34deeab4c4e52ffa21866",
          "sha1": "2b1c2fd3c4fa58f3e65ced72d242499c0816cb4f",
          "md5": "79a281f7966db6575b640782a4209269"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.13-javadoc.jar",
          "url": "tor-android-0.4.9.13-javadoc.jar",
          "size": 455484,
          "sha512": "ad16cb96f24ee74147dd4be953970871b9371fc176aeb91d0fdbc5ded83c7eb4f98aa0f7d0b0d5a08d3636f1ae1db62fd8cf98fda9f932b4151cfa4d8f86133c",
          "sha256": "9a70085f7f2e05337620b305c0f55a4fb220b31ecc00299bfe8080e482c8c859",
          "sha1": "fa0e812bb1ed0829913bcb85cb45b21e37ad68b8",
          "md5": "b570008c33ff7a71aef44b484598e72c"
        }
      ]
    }
  ]
}
