{
  "formatVersion": "1.1",
  "component": {
    "group": "org.proofmode",
    "module": "android-opentimestamps",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk15to18",
          "version": {
            "requires": "1.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-opentimestamps-1.0.27.aar",
          "url": "android-opentimestamps-1.0.27.aar",
          "size": 82153,
          "sha512": "6b46329c7dea906b7e1f8f40aa850ad2e29350824e31ddea93ce0c2e593b09d575ff199220a1ac7a40f4d561900c78a1ae30cf89a29eb0e90042a4439b13c7a3",
          "sha256": "9ea4ff6fc61fa2420bb6a8b7cac4c959923897e3a25309ba4a7810bd66b21f5b",
          "sha1": "ee518b85c50e58c001fca859ff9e460090eb57b0",
          "md5": "22d1ca240b49dda397d8a5e1b73cf4e6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15to18",
          "version": {
            "requires": "1.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "org.bitcoinj",
          "module": "bitcoinj-core",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "org.proofmode",
          "module": "android-libproofmode",
          "version": {
            "requires": "1.0.30"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk15to18",
          "version": {
            "requires": "1.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-opentimestamps-1.0.27.aar",
          "url": "android-opentimestamps-1.0.27.aar",
          "size": 82153,
          "sha512": "6b46329c7dea906b7e1f8f40aa850ad2e29350824e31ddea93ce0c2e593b09d575ff199220a1ac7a40f4d561900c78a1ae30cf89a29eb0e90042a4439b13c7a3",
          "sha256": "9ea4ff6fc61fa2420bb6a8b7cac4c959923897e3a25309ba4a7810bd66b21f5b",
          "sha1": "ee518b85c50e58c001fca859ff9e460090eb57b0",
          "md5": "22d1ca240b49dda397d8a5e1b73cf4e6"
        }
      ]
    }
  ]
}
