{
  "formatVersion": "1.1",
  "component": {
    "group": "matrix",
    "module": "sdk2",
    "version": "1.4.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "com.atlassian.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdk2-1.4.14.aar",
          "url": "sdk2-1.4.14.aar",
          "size": 9543409,
          "sha512": "3520fcfce431b63dd784126e990a537a1914b3acbd0e40ab3b6a10c4311039ea3412ebf65b63e4b967ae53badef2675b452f2ac8cc9fa9ddc4141e80f4d4e98c",
          "sha256": "6a1f3c126677f065b18a69a713e79724743bc27ebea79039456fc4e98560c75e",
          "sha1": "047316185bdaccd268588f290eee708b328cfd7f",
          "md5": "671ec44944223f02d6f9232531833716"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "com.atlassian.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-bom",
          "version": {
            "requires": "4.10.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor"
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.Zhuinden",
          "module": "realm-monarchy",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.matrix.android",
          "module": "olm-sdk",
          "version": {
            "requires": "3.2.12"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.42"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "transcoder",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "org.apache.sanselan",
          "module": "sanselan",
          "version": {
            "requires": "0.97-incubator"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.12.50"
          }
        }
      ],
      "files": [
        {
          "name": "sdk2-1.4.14.aar",
          "url": "sdk2-1.4.14.aar",
          "size": 9543409,
          "sha512": "3520fcfce431b63dd784126e990a537a1914b3acbd0e40ab3b6a10c4311039ea3412ebf65b63e4b967ae53badef2675b452f2ac8cc9fa9ddc4141e80f4d4e98c",
          "sha256": "6a1f3c126677f065b18a69a713e79724743bc27ebea79039456fc4e98560c75e",
          "sha1": "047316185bdaccd268588f290eee708b328cfd7f",
          "md5": "671ec44944223f02d6f9232531833716"
        }
      ]
    }
  ]
}
