{
  "formatVersion": "1.1",
  "component": {
    "group": "org.witness",
    "module": "android-libproofmode",
    "version": "1.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk15to18",
          "version": {
            "requires": "1.71"
          }
        }
      ],
      "files": [
        {
          "name": "android-libproofmode-1.0.20.aar",
          "url": "android-libproofmode-1.0.20.aar",
          "size": 73317,
          "sha512": "bb6f1d1d91c574391bb7cdbf47194f3b05c2766132bc6221f06ba3d1e46890fb15728f3e55cabbfd22ec7f6e9818d873c512f461c30d22b18fbc06a2c88c23eb",
          "sha256": "eda2861fad6eec3f88bb50eed7dbc8086be562454953f2e63f30a9bc480bf3f3",
          "sha1": "521f186fe8f17b6ac6aa64697f10fa11cd67c11f",
          "md5": "733a359f5b54101f1a8a53dfa27d3b09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15to18",
          "version": {
            "requires": "1.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk15to18",
          "version": {
            "requires": "1.71"
          }
        }
      ],
      "files": [
        {
          "name": "android-libproofmode-1.0.20.aar",
          "url": "android-libproofmode-1.0.20.aar",
          "size": 73317,
          "sha512": "bb6f1d1d91c574391bb7cdbf47194f3b05c2766132bc6221f06ba3d1e46890fb15728f3e55cabbfd22ec7f6e9818d873c512f461c30d22b18fbc06a2c88c23eb",
          "sha256": "eda2861fad6eec3f88bb50eed7dbc8086be562454953f2e63f30a9bc480bf3f3",
          "sha1": "521f186fe8f17b6ac6aa64697f10fa11cd67c11f",
          "md5": "733a359f5b54101f1a8a53dfa27d3b09"
        }
      ]
    }
  ]
}
