{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "tor-android",
    "version": "0.4.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.6.aar",
          "url": "tor-android-0.4.9.6.aar",
          "size": 15019440,
          "sha512": "dffff901f846fee7c3a1de3e547e444dc0b884e95a57bd78641e23a7778150323650171c005d83c5ccc3b9e99044d0c764ca04bf49ca01dee75f86ba059da0a9",
          "sha256": "45dfecd0ef3acd82bbab41ff733db3e3853e5fe417266cb578d2d46e2274a0bc",
          "sha1": "feb03b3cdd1b1035e0080df7c93ae586d7373777",
          "md5": "5b95af3665424e8acc2a2399ceee0362"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.6.aar",
          "url": "tor-android-0.4.9.6.aar",
          "size": 15019440,
          "sha512": "dffff901f846fee7c3a1de3e547e444dc0b884e95a57bd78641e23a7778150323650171c005d83c5ccc3b9e99044d0c764ca04bf49ca01dee75f86ba059da0a9",
          "sha256": "45dfecd0ef3acd82bbab41ff733db3e3853e5fe417266cb578d2d46e2274a0bc",
          "sha1": "feb03b3cdd1b1035e0080df7c93ae586d7373777",
          "md5": "5b95af3665424e8acc2a2399ceee0362"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.6-sources.jar",
          "url": "tor-android-0.4.9.6-sources.jar",
          "size": 6865,
          "sha512": "86400af00a51cae18b8dae4b61d4aa2c6cdb5b1b2b9e56e909e02e2c6f21ede5d65ab71ea6211430a270a68a8d2ec2732510d75608220ee3d55ff4d7969ebba2",
          "sha256": "246865df15e476eb314fca39d262efad1907972381e7e6bdcd05e4c34b3334c1",
          "sha1": "d99d1fe99f5d9de1c67125458d3032c5e3b0521d",
          "md5": "02063082baee5f1cc601ca31207ec36a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.6-javadoc.jar",
          "url": "tor-android-0.4.9.6-javadoc.jar",
          "size": 300978,
          "sha512": "1467ef97fdd28cc3f2a47be16e48ed6839b340c344bac62bf0ba93349b72b6441ebe5e859fcab5d94b33bb54d527930a9d6ea48278b62f80625f847c7ecdbb6d",
          "sha256": "5bb78fa5f4445aea7f23e14110374143aad2d5b3ee82dc544f7b3aa3d1c97a26",
          "sha1": "7da606cc5034d209edc691b0d4480fbb068737f1",
          "md5": "4590738c52c9f4ec0ef3b03c8bf6d9c8"
        }
      ]
    }
  ]
}
