{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "tor-android",
    "version": "0.4.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.8.12.aar",
          "url": "tor-android-0.4.8.12.aar",
          "size": 13324376,
          "sha512": "f69c50bf89682fdc781209c04fae3299fc1bce61beaadc57bb51d2cfaf2c55886f6507cc721c405d0ab12d580d744ff8cc6a430a487a72b11449e8cadbf59911",
          "sha256": "d158334d247464aab386ef73f90663c60cfc35e60028c5ea9ad858c229d0d29d",
          "sha1": "fceebc5085e8eac558010ea05990a7709690dcfc",
          "md5": "2641411151a0b25d29e083ebd13db415"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.8.12.aar",
          "url": "tor-android-0.4.8.12.aar",
          "size": 13324376,
          "sha512": "f69c50bf89682fdc781209c04fae3299fc1bce61beaadc57bb51d2cfaf2c55886f6507cc721c405d0ab12d580d744ff8cc6a430a487a72b11449e8cadbf59911",
          "sha256": "d158334d247464aab386ef73f90663c60cfc35e60028c5ea9ad858c229d0d29d",
          "sha1": "fceebc5085e8eac558010ea05990a7709690dcfc",
          "md5": "2641411151a0b25d29e083ebd13db415"
        }
      ]
    }
  ]
}
