{
  "formatVersion": "1.1",
  "component": {
    "group": "org.torproject",
    "module": "arti-mobile",
    "version": "1.7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-1.7.0.1.aar",
          "url": "arti-mobile-1.7.0.1.aar",
          "size": 19663322,
          "sha512": "f14d2d1e8463f9c397dce6e2a1a42a8ed28ac3499e8f56c18a3c9d42bf4b290b354ebd8e87bd70e4cfd0a80339b88a8892b3f529903c37f78e08188de16c756c",
          "sha256": "cbdb34ce3cdb32f755f25f6dd05a2d1eb9a44025a17ec9202729816e2a3af05b",
          "sha1": "cd05d72cabe12e0ca54df0d545e9bd521204b7a8",
          "md5": "657971ecfd328583ef19e5a19860c3d6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-1.7.0.1.aar",
          "url": "arti-mobile-1.7.0.1.aar",
          "size": 19663322,
          "sha512": "f14d2d1e8463f9c397dce6e2a1a42a8ed28ac3499e8f56c18a3c9d42bf4b290b354ebd8e87bd70e4cfd0a80339b88a8892b3f529903c37f78e08188de16c756c",
          "sha256": "cbdb34ce3cdb32f755f25f6dd05a2d1eb9a44025a17ec9202729816e2a3af05b",
          "sha1": "cd05d72cabe12e0ca54df0d545e9bd521204b7a8",
          "md5": "657971ecfd328583ef19e5a19860c3d6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "arti-mobile-1.7.0.1-sources.jar",
          "url": "arti-mobile-1.7.0.1-sources.jar",
          "size": 9915,
          "sha512": "a7f56eaae55cb8433a6d69a441c5b728b5ae592f1f2e43db86391ecfb097ee28f648486c16939dc9d828e3bacd0c8081566ad68e183ef535f20ac1f024c5b17e",
          "sha256": "891a279a6ca23de3b56deda41cefaabc61788b89b5e85f3e7a93649c03a0ca90",
          "sha1": "26ab6058ab99f0c303a700c396b56aa951a24fa0",
          "md5": "ef33e47485828461d7880210edaf5781"
        }
      ]
    }
  ]
}
