{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "durindoor",
    "version": "0.0.6-debug",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "durindoor-0.0.6-debug.aar",
          "url": "durindoor-0.0.6-debug.aar",
          "size": 467019,
          "sha512": "e654c1fb10cd792bb9e7202831ff2b7da9f27cde9b264b9c91a73e578c7a43d5508b629d1ab48823a925d935668790f2589bf803a2d9bf3dffb88fccf62fecb8",
          "sha256": "6d6913fdc30c206fe420e7b17d7185865a4f5c1a036fd192f988b8fb47f316bb",
          "sha1": "1cd3a05d4f5c2bf396bd032595861bd667ee9c81",
          "md5": "db2729547ebb5445a7cd6d72df3f8d69"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "durindoor-0.0.6-debug.aar",
          "url": "durindoor-0.0.6-debug.aar",
          "size": 467019,
          "sha512": "e654c1fb10cd792bb9e7202831ff2b7da9f27cde9b264b9c91a73e578c7a43d5508b629d1ab48823a925d935668790f2589bf803a2d9bf3dffb88fccf62fecb8",
          "sha256": "6d6913fdc30c206fe420e7b17d7185865a4f5c1a036fd192f988b8fb47f316bb",
          "sha1": "1cd3a05d4f5c2bf396bd032595861bd667ee9c81",
          "md5": "db2729547ebb5445a7cd6d72df3f8d69"
        }
      ]
    }
  ]
}
