{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "arti-mobile-ex",
    "version": "1.1.0-local-release",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "arti-mobile-ex-1.1.0-local-release.aar",
          "url": "arti-mobile-ex-1.1.0-local-release.aar",
          "size": 46807295,
          "sha512": "1b556212ddecedf6d1f58a42c89bf8548bb5fa26540d55f25e105d7f6784202a96b26f9071937d83004f5c67f06e04f19a20d2864786996e8fff674bef798af6",
          "sha256": "3b6831ece5614cfe21ff0ed25b88a519703bfb3c0780a7139e41c8760d99219a",
          "sha1": "79d9e62dcb7fa57da1bb34a07280686e39dc8850",
          "md5": "768d23cfc24938757fb6041c9b583425"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-ex-1.1.0-local-release.aar",
          "url": "arti-mobile-ex-1.1.0-local-release.aar",
          "size": 46807295,
          "sha512": "1b556212ddecedf6d1f58a42c89bf8548bb5fa26540d55f25e105d7f6784202a96b26f9071937d83004f5c67f06e04f19a20d2864786996e8fff674bef798af6",
          "sha256": "3b6831ece5614cfe21ff0ed25b88a519703bfb3c0780a7139e41c8760d99219a",
          "sha1": "79d9e62dcb7fa57da1bb34a07280686e39dc8850",
          "md5": "768d23cfc24938757fb6041c9b583425"
        }
      ]
    }
  ]
}
