{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "arti-mobile-ex",
    "version": "1.1.0.1-local-debug",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "arti-mobile-ex-1.1.0.1-local-debug.aar",
          "url": "arti-mobile-ex-1.1.0.1-local-debug.aar",
          "size": 46820686,
          "sha512": "2b5a7d27a2399f892abcfc9bbdeff0c9f2d77fab0e572ed129e1e2bbcc84594cf7f886a420ab2d3fa1eaa902f23b3debb45050778f40ba8b5beea11e624bb905",
          "sha256": "fdb783c626cf63b98f793c13700b4801d8c6437fc4319bf93722cc973697c4e3",
          "sha1": "72bd19b0e81abc4f744eab5b36398737adbe9eec",
          "md5": "ebc3711016b7d2787d66b0613caf8b52"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-ex-1.1.0.1-local-debug.aar",
          "url": "arti-mobile-ex-1.1.0.1-local-debug.aar",
          "size": 46820686,
          "sha512": "2b5a7d27a2399f892abcfc9bbdeff0c9f2d77fab0e572ed129e1e2bbcc84594cf7f886a420ab2d3fa1eaa902f23b3debb45050778f40ba8b5beea11e624bb905",
          "sha256": "fdb783c626cf63b98f793c13700b4801d8c6437fc4319bf93722cc973697c4e3",
          "sha1": "72bd19b0e81abc4f744eab5b36398737adbe9eec",
          "md5": "ebc3711016b7d2787d66b0613caf8b52"
        }
      ]
    }
  ]
}
