{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "tor-android",
    "version": "0.4.9.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.13.1.aar",
          "url": "tor-android-0.4.9.13.1.aar",
          "size": 12957516,
          "sha512": "6a4aaf9de0e9c157400965874bce4f317bded30593ad034de8215e3d0c286446099b7a114e9faab52cc56f2b2e7ff59556b2208045630c2f9d1f58faa1c8877c",
          "sha256": "6daf207315ce733ee96e850ef9e1cdef0ed5c5f407f29206f0438b42abf58f6a",
          "sha1": "25fe7c654d54a88220458d53c281527dae4b603c",
          "md5": "8988db27245096dd5089dcc21e5a8a09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.13.1.aar",
          "url": "tor-android-0.4.9.13.1.aar",
          "size": 12957516,
          "sha512": "6a4aaf9de0e9c157400965874bce4f317bded30593ad034de8215e3d0c286446099b7a114e9faab52cc56f2b2e7ff59556b2208045630c2f9d1f58faa1c8877c",
          "sha256": "6daf207315ce733ee96e850ef9e1cdef0ed5c5f407f29206f0438b42abf58f6a",
          "sha1": "25fe7c654d54a88220458d53c281527dae4b603c",
          "md5": "8988db27245096dd5089dcc21e5a8a09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.13.1-sources.jar",
          "url": "tor-android-0.4.9.13.1-sources.jar",
          "size": 6653,
          "sha512": "f2786936d7356e39b55e714b19c73d62f5eb4362c734d704585ea6416d19cde6d9fca8b51c28b1ee8c964598865bcda5c38d47ffb8858ae46b5f39e9af136192",
          "sha256": "f8d5d5ba2e04f16fcf393df9fc75b9a3e9e6d98547d36cc08bc8cc8cd7fa3f7e",
          "sha1": "818aa828502bfa8fa535ce64aeba82d8f7613f0f",
          "md5": "6eb921430cde8088ebad1eacf4d0e5f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.13.1-javadoc.jar",
          "url": "tor-android-0.4.9.13.1-javadoc.jar",
          "size": 455484,
          "sha512": "ad16cb96f24ee74147dd4be953970871b9371fc176aeb91d0fdbc5ded83c7eb4f98aa0f7d0b0d5a08d3636f1ae1db62fd8cf98fda9f932b4151cfa4d8f86133c",
          "sha256": "9a70085f7f2e05337620b305c0f55a4fb220b31ecc00299bfe8080e482c8c859",
          "sha1": "fa0e812bb1ed0829913bcb85cb45b21e37ad68b8",
          "md5": "b570008c33ff7a71aef44b484598e72c"
        }
      ]
    }
  ]
}
