{
  "formatVersion": "1.1",
  "component": {
    "group": "matrix",
    "module": "sdk2",
    "version": "1.3.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "sdk2-1.3.18.1.aar",
          "url": "sdk2-1.3.18.1.aar",
          "size": 9026643,
          "sha512": "0176e07696396c0b8ee3bb47a57871efab266585ab21398f98c7c649cded09aed4050d6cfad97a86d3502d85e896809503a468a58713a38ed85d0284b66ed56a",
          "sha256": "ea393c7184ed5053288db8621573005f2383c210f1a2af6f811ec83daf52d7d8",
          "sha1": "ef97c4b41889bc7812b85cc3d1e41a55b038dd92",
          "md5": "a6d4d1572675cf5cb330ff237f3aaa8e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-library",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-android-kotlin-extensions",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "io.realm",
          "module": "realm-annotations",
          "version": {
            "requires": "10.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-bom",
          "version": {
            "requires": "4.9.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor"
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection"
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "io.noties.markwon",
          "module": "core",
          "version": {
            "requires": "4.6.2"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "com.github.Zhuinden",
          "module": "realm-monarchy",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "io.arrow-kt",
          "module": "arrow-instances-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.matrix.android",
          "module": "olm-sdk",
          "version": {
            "requires": "3.2.10"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.40.5"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.facebook.stetho",
          "module": "stetho-okhttp3",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "transcoder",
          "version": {
            "requires": "0.10.4"
          }
        },
        {
          "group": "org.apache.sanselan",
          "module": "sanselan",
          "version": {
            "requires": "0.97-incubator"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.12.42"
          }
        }
      ],
      "files": [
        {
          "name": "sdk2-1.3.18.1.aar",
          "url": "sdk2-1.3.18.1.aar",
          "size": 9026643,
          "sha512": "0176e07696396c0b8ee3bb47a57871efab266585ab21398f98c7c649cded09aed4050d6cfad97a86d3502d85e896809503a468a58713a38ed85d0284b66ed56a",
          "sha256": "ea393c7184ed5053288db8621573005f2383c210f1a2af6f811ec83daf52d7d8",
          "sha1": "ef97c4b41889bc7812b85cc3d1e41a55b038dd92",
          "md5": "a6d4d1572675cf5cb330ff237f3aaa8e"
        }
      ]
    }
  ]
}
