{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "tor-android",
    "version": "0.4.8.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.8.19.aar",
          "url": "tor-android-0.4.8.19.aar",
          "size": 14973075,
          "sha512": "bcfb52257ee5b2c7dc4166eaca301a90935fc40681a821da0f69916febca7e1d408e7803c4922ac0c385b2356f8dc893f2e52e62fb7bcd353cfdff5025a3fef2",
          "sha256": "ba97f8ded25c1e390a0acc937193c4643e6a8afa4a66710813c22c0dd50db9fa",
          "sha1": "a4ae51f71dbc5ae634a4d25fb9f2b2c230e835bc",
          "md5": "0e1e002f828f9cd5f777aa747882bd7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.8.19.aar",
          "url": "tor-android-0.4.8.19.aar",
          "size": 14973075,
          "sha512": "bcfb52257ee5b2c7dc4166eaca301a90935fc40681a821da0f69916febca7e1d408e7803c4922ac0c385b2356f8dc893f2e52e62fb7bcd353cfdff5025a3fef2",
          "sha256": "ba97f8ded25c1e390a0acc937193c4643e6a8afa4a66710813c22c0dd50db9fa",
          "sha1": "a4ae51f71dbc5ae634a4d25fb9f2b2c230e835bc",
          "md5": "0e1e002f828f9cd5f777aa747882bd7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.8.19-sources.jar",
          "url": "tor-android-0.4.8.19-sources.jar",
          "size": 6842,
          "sha512": "8b64a982c8aed8cb2dfd1e9ce8182828ae8663ba11b4aec809540eec8ab7fb09da43ec655b57f19b6b45dca041f397410ba7fc7d9c37c0514e816500a5cd44be",
          "sha256": "82f1b964607ce5851fe41622e5e837f9904ef503116ce05dfac1de0c69935daf",
          "sha1": "65c7e620e0801cacbd50dc64404f5c9b3c86cd03",
          "md5": "7b8af3678f542335e736a37f3a81b1a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.8.19-javadoc.jar",
          "url": "tor-android-0.4.8.19-javadoc.jar",
          "size": 300827,
          "sha512": "18d26df0422cbba2e099e69ed882a07451d42a3c8d1f9377577c8be3c6a651cda6f7769ecdf996528bdd0ad00f2fe101d0a467d35da3a7996d9bd237018d6803",
          "sha256": "c85495ed6316501c00ba0bdc11db3ee0abf6844d4b914ea3ad2d293c755dc5c4",
          "sha1": "e4b9b1ecb11f5703bf3040e5dd9169f8c592ba64",
          "md5": "20f1dad7b1419811667010ec6d51d40b"
        }
      ]
    }
  ]
}
