{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "tor-android",
    "version": "0.4.9.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.9.1.aar",
          "url": "tor-android-0.4.9.9.1.aar",
          "size": 12939868,
          "sha512": "6f746941b7951d65aa3f2b07b6d074572f5103853245e42a26d878fcd2b106c508434d35637f2a3b0424df4247de46739dafbb9ff831beb638c9ca78118cf39e",
          "sha256": "84e8624b552f6e065f4877a332ef2a3d7af7e6b8653fead8417b6f47d13fcf5b",
          "sha1": "edb450789a6bea21de43f5e337e1509f7c9f7fbf",
          "md5": "564276c1d2088229d908506b524578fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.9.1.aar",
          "url": "tor-android-0.4.9.9.1.aar",
          "size": 12939868,
          "sha512": "6f746941b7951d65aa3f2b07b6d074572f5103853245e42a26d878fcd2b106c508434d35637f2a3b0424df4247de46739dafbb9ff831beb638c9ca78118cf39e",
          "sha256": "84e8624b552f6e065f4877a332ef2a3d7af7e6b8653fead8417b6f47d13fcf5b",
          "sha1": "edb450789a6bea21de43f5e337e1509f7c9f7fbf",
          "md5": "564276c1d2088229d908506b524578fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.9.1-sources.jar",
          "url": "tor-android-0.4.9.9.1-sources.jar",
          "size": 6861,
          "sha512": "44fa620eeee204fddcbae8593f03bf7841f74f5053007f6fefb45f9e8ff39fe2af1a8ac7a381ba295ecab4a12f7ee3a2f07df6f9183dbe565169042a4a112e30",
          "sha256": "1d9ce7ab6defe63735e4492d6621a17b827da919664ddf0f6fd69343307fac1f",
          "sha1": "fa1a395ac346d1a1ea594e4b1674a9e29ac7f08f",
          "md5": "bbf20f660caf9b24b92997f569b09389"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.9.1-javadoc.jar",
          "url": "tor-android-0.4.9.9.1-javadoc.jar",
          "size": 301087,
          "sha512": "692595fac46b953832d72558ea85d8802e600031c7fec225e2074fa455829ab3f69f5fc79a25dabfc092daddd5ed4a63e5ef105de793c997891cac0fa339a726",
          "sha256": "aa5994843de46133692830efa9778d4a4215a02957dd1a15a88feadb913bceef",
          "sha1": "a987f1eeddaa4e428dd878add0d8c72a5e07e670",
          "md5": "a6f6b06a1dc8e0c687b4304cef598640"
        }
      ]
    }
  ]
}
