{
  "formatVersion": "1.1",
  "component": {
    "group": "org.proofmode",
    "module": "android-libproofmode",
    "version": "1.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk15to18",
          "version": {
            "requires": "1.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-libproofmode-1.0.29.aar",
          "url": "android-libproofmode-1.0.29.aar",
          "size": 85157,
          "sha512": "fab8b8f9114c4950397a3628cb9f57bc02e5eadf0ddc29205241495e553b463323a8bdaace3009c7bc8875b537bbfdd0cf6276e4dd2913e9277da58d87ac3294",
          "sha256": "89dea83bf8fb38bb91e254244fad1887616c3b61a6ba66cde068f40e16098f59",
          "sha1": "d798f48779090039940ee6bc2df399229a165afd",
          "md5": "5a7a02b8a00c0b66c92562b8ded20a27"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15to18",
          "version": {
            "requires": "1.72"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15to18",
          "version": {
            "requires": "1.72"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpg-jdk15to18",
          "version": {
            "requires": "1.71"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "android-libproofmode-1.0.29.aar",
          "url": "android-libproofmode-1.0.29.aar",
          "size": 85157,
          "sha512": "fab8b8f9114c4950397a3628cb9f57bc02e5eadf0ddc29205241495e553b463323a8bdaace3009c7bc8875b537bbfdd0cf6276e4dd2913e9277da58d87ac3294",
          "sha256": "89dea83bf8fb38bb91e254244fad1887616c3b61a6ba66cde068f40e16098f59",
          "sha1": "d798f48779090039940ee6bc2df399229a165afd",
          "md5": "5a7a02b8a00c0b66c92562b8ded20a27"
        }
      ]
    }
  ]
}
