{
  "formatVersion": "1.1",
  "component": {
    "group": "org.torproject",
    "module": "arti-mobile",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-1.7.0.aar",
          "url": "arti-mobile-1.7.0.aar",
          "size": 19664032,
          "sha512": "194aea8b400c1f957aafc8805fa9cbd1a3e22042501ec9b8cd8c8ba374ff2bb7678fbb64585c354a947bbfff2f15331f4b38aeccb3cd37675c1fd7b89cc9b2ed",
          "sha256": "534e25aa387575f1c27558af153e9cbddd5afd47ad03866865c328ea60e04b2f",
          "sha1": "5e1cc41698c11a9f3f81e46ea5bc1439181438b4",
          "md5": "fe37b881ca66f7b3bb5e29c6e02a96a2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-1.7.0.aar",
          "url": "arti-mobile-1.7.0.aar",
          "size": 19664032,
          "sha512": "194aea8b400c1f957aafc8805fa9cbd1a3e22042501ec9b8cd8c8ba374ff2bb7678fbb64585c354a947bbfff2f15331f4b38aeccb3cd37675c1fd7b89cc9b2ed",
          "sha256": "534e25aa387575f1c27558af153e9cbddd5afd47ad03866865c328ea60e04b2f",
          "sha1": "5e1cc41698c11a9f3f81e46ea5bc1439181438b4",
          "md5": "fe37b881ca66f7b3bb5e29c6e02a96a2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "arti-mobile-1.7.0-sources.jar",
          "url": "arti-mobile-1.7.0-sources.jar",
          "size": 10071,
          "sha512": "698ee3d12f4998dcb777557d01b783095618ded7b2b85b8296c27fdec068532553fa04f6062094d080a7746534f0efb6bf2f8c8d1a6ec4957e9e7d0eb22df2b1",
          "sha256": "236b2b7348b8624f64a2d80ce33efe39a508f7d9dd50ef70e0a1168d514b5aa2",
          "sha1": "05cc19cf1c6578f9a218e636968f37f2bffc7824",
          "md5": "ac8ecb0342fe65108c5ca5dc3208ad1b"
        }
      ]
    }
  ]
}
