{
  "formatVersion": "1.1",
  "component": {
    "group": "org.torproject",
    "module": "arti-mobile",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-1.7.0.aar",
          "url": "arti-mobile-1.7.0.aar",
          "size": 19663981,
          "sha512": "95e0a2b27c85e4f9f83e0e8d0e43f41095c08cddc81bac66e26ad66de847e5a02fd896138d4521abb0bbeaf0bb13d42c594253860c602d1afa0c9550da032c3c",
          "sha256": "7fdf5ca3144a61095d22b779943d5ea3af8142667ab1901985194a99a4459aa5",
          "sha1": "78e37a4b121658bf6891ee1ce3772d5229968d56",
          "md5": "9baa573ec44c14ffc92a79dbbce1dfab"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "arti-mobile-1.7.0.aar",
          "url": "arti-mobile-1.7.0.aar",
          "size": 19663981,
          "sha512": "95e0a2b27c85e4f9f83e0e8d0e43f41095c08cddc81bac66e26ad66de847e5a02fd896138d4521abb0bbeaf0bb13d42c594253860c602d1afa0c9550da032c3c",
          "sha256": "7fdf5ca3144a61095d22b779943d5ea3af8142667ab1901985194a99a4459aa5",
          "sha1": "78e37a4b121658bf6891ee1ce3772d5229968d56",
          "md5": "9baa573ec44c14ffc92a79dbbce1dfab"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "arti-mobile-1.7.0-sources.jar",
          "url": "arti-mobile-1.7.0-sources.jar",
          "size": 9915,
          "sha512": "a7f56eaae55cb8433a6d69a441c5b728b5ae592f1f2e43db86391ecfb097ee28f648486c16939dc9d828e3bacd0c8081566ad68e183ef535f20ac1f024c5b17e",
          "sha256": "891a279a6ca23de3b56deda41cefaabc61788b89b5e85f3e7a93649c03a0ca90",
          "sha1": "26ab6058ab99f0c303a700c396b56aa951a24fa0",
          "md5": "ef33e47485828461d7880210edaf5781"
        }
      ]
    }
  ]
}
