{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "tor-android",
    "version": "0.4.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.8.13.aar",
          "url": "tor-android-0.4.8.13.aar",
          "size": 13334121,
          "sha512": "8f1f34a736f4115e13549e81c9879de7837d20359e6fad3fd60569dc92e78ed7b29076b092429944173ed19488904bc23dd4a575c0e7c38b2a8ccd9f82a53c9f",
          "sha256": "ea2c4d209751563008495b826cb07d0878231d242747b9c8395486c8cffc424a",
          "sha1": "05ac4a4fd70ca8b22477c7f51161efe3915283d4",
          "md5": "741b0e7261369a025c941053d7a1424c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.8.13.aar",
          "url": "tor-android-0.4.8.13.aar",
          "size": 13334121,
          "sha512": "8f1f34a736f4115e13549e81c9879de7837d20359e6fad3fd60569dc92e78ed7b29076b092429944173ed19488904bc23dd4a575c0e7c38b2a8ccd9f82a53c9f",
          "sha256": "ea2c4d209751563008495b826cb07d0878231d242747b9c8395486c8cffc424a",
          "sha1": "05ac4a4fd70ca8b22477c7f51161efe3915283d4",
          "md5": "741b0e7261369a025c941053d7a1424c"
        }
      ]
    }
  ]
}
