{
  "formatVersion": "1.1",
  "component": {
    "group": "info.guardianproject",
    "module": "tor-android",
    "version": "0.4.9.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.14.aar",
          "url": "tor-android-0.4.9.14.aar",
          "size": 12976254,
          "sha512": "4045ac99fe49feb2cc7ddacaf8479cccc45ac4cc23e6413c6d936bf63eb19b19f2eb1d04409e2c12cdcfcbaaf99c9b91318e4c70eb4872d19984f51a3bf8589d",
          "sha256": "28ff2bb6d4d42eabe57183dedd7a97fce77e8ce4b6f5af6fa03993b3ca054edd",
          "sha1": "f31a06e885a46009b701b013f369f622f0728c87",
          "md5": "81d707e5bb6be090641a8fcd6e63665d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "info.guardianproject",
          "module": "jtorctl",
          "version": {
            "requires": "0.4.5.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "tor-android-0.4.9.14.aar",
          "url": "tor-android-0.4.9.14.aar",
          "size": 12976254,
          "sha512": "4045ac99fe49feb2cc7ddacaf8479cccc45ac4cc23e6413c6d936bf63eb19b19f2eb1d04409e2c12cdcfcbaaf99c9b91318e4c70eb4872d19984f51a3bf8589d",
          "sha256": "28ff2bb6d4d42eabe57183dedd7a97fce77e8ce4b6f5af6fa03993b3ca054edd",
          "sha1": "f31a06e885a46009b701b013f369f622f0728c87",
          "md5": "81d707e5bb6be090641a8fcd6e63665d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.14-sources.jar",
          "url": "tor-android-0.4.9.14-sources.jar",
          "size": 6651,
          "sha512": "bda027123c0fa40f25c7ee453ebf2b8ecc1aeaa913515b3c5f3e22d8ac34878accd4cd836812d02e1e3ea557fedc9f7c0c8ee9329cd319bda14f1216d15f0023",
          "sha256": "095118a41782a91b9002038461c4c6a65f5c41bc6f5a37323362eceaf0088a2b",
          "sha1": "81568f4eaf31ea693aa76b6d86341c6720f89b09",
          "md5": "4c73203181e5b021975f9350533941ef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tor-android-0.4.9.14-javadoc.jar",
          "url": "tor-android-0.4.9.14-javadoc.jar",
          "size": 455484,
          "sha512": "ad16cb96f24ee74147dd4be953970871b9371fc176aeb91d0fdbc5ded83c7eb4f98aa0f7d0b0d5a08d3636f1ae1db62fd8cf98fda9f932b4151cfa4d8f86133c",
          "sha256": "9a70085f7f2e05337620b305c0f55a4fb220b31ecc00299bfe8080e482c8c859",
          "sha1": "fa0e812bb1ed0829913bcb85cb45b21e37ad68b8",
          "md5": "b570008c33ff7a71aef44b484598e72c"
        }
      ]
    }
  ]
}
